baseURL: 'https://innersourcecommons.net/'
title: InnerSource Commons

languages:
  en:
    languageName: English
    weight: 1
    menu:
      main:
        - name: Learn
          URL: learn
          weight: 1
          identifier: learn
        - name: Books
          parent: learn
          URL: learn/books
          weight: 2
        - name: Learning Path
          parent: learn
          URL: learn/learning-path
          weight: 3
        - name: Patterns
          parent: learn
          URL: learn/patterns
          weight: 4
        - name: Events
          URL: events
          weight: 2
        - name: Community
          identifier: community
          URL: community
          weight: 3
        - name: InnerSource in Action
          URL: community/action
          parent: community
          weight: 1
        - name: About
          identifier: about
          URL: about
          weight: 4
        - name: Board & Governance
          URL: about/board
          parent: about
          weight: 1
        - name: Code of Conduct
          URL: about/codeofconduct
          parent: about
          weight: 2
        - name: Contact Us
          URL: about/contact
          parent: about
          weight: 3
      footer_left:
        - name: Events
          URL: events
          weight: 1
        - name: Learn
          URL: learn
          weight: 2
        - name: Community
          URL: community
          weight: 3
          pre: _blank
        - name: About
          URL: about
          weight: 4
#      footer_middle:
#      footer_right:
  ru:
    languageName: Русский
    weight: 2
    menu:
      main:
        - name: События
          URL: ru/events
          weight: 1
        - name: Обучение
          URL: ru/learn
          weight: 2
        - name: Паттерны
          URL: https://innersourcecommons.gitbook.io/innersource-patterns/
          weight: 3
          pre: _blank
        - name: О сообществе
          URL: ru/about
          weight: 4
paginate: '3'
summaryLength: '15'
disqusShortname: ''
googleAnalytics: ''
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/themify-icons/themify-icons.css
      - link: plugins/slick/slick.css
      - link: plugins/youmax/youmax.css
      - link: plugins/bootstrap-select/css/bootstrap-select.min.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/youmax/youmax.js
      - link: plugins/bootstrap-select/js/bootstrap-select.min.js
  logo: images/logo.png
  logo_width: 200px
  description: This is meta description
  author: Themefisher
  contact_form_action: '#'
  footer_content: >-
    The site content is licensed under a CC-BY-SA license unless otherwise marked.
  copyright: >-
    Design by [Themefisher](https://themefisher.com/) and [Gethugothemes](https://gethugothemes.com/),
    icons by [Freepik Storyset](https://storyset.com/people)
  preloader:
    enable: false
    preloader: ''
  navigation_button:
    enable: true
    label: Join Slack
    link: slack
  social:
    - title: github
      icon: ti-github
      link: 'http://github.com/InnerSourceCommons'
    - title: youtube
      icon: ti-youtube
      link: 'https://www.youtube.com/channel/UCoSPSd6Or4F_vpjo4SmyoEA'
    - title: twitter
      icon: ti-twitter-alt
      link: 'http://twitter.com/InnerSourceOrg'
    - title: linkedin
      icon: ti-linkedin
      link: 'https://linkedin.com/company/innersourcecommons'
